notebooks/walkthrough.ipynb
Note that images will only render upon repo becoming public.
=> Fixes notebook URL from relative path to static site to render correctly in GH

README.md
=> Change link for metrics

lumigator/python/mzai/backend/services/completions.py, lumigator/python/mzai/backend/services/experiments.py, lumigator/python/mzai/backend/settings.py
This PR moves the environment variables retrieval to `settings.py`.
=> [LUMI-33] Move env vars to settings

.devcontainer/docker-compose-local.yaml
Modified our dockercompose file to enable localhost accessible from within lumigator so it can serve files locally with localstack without changing lumigator code or adding extra env vars 
Upload files to lumigator and download them.
none
=> Added extra hosts to match localhost from lumigator to local laptop

.devcontainer/README.md, README.md
Documentation on the environment variables is added to the README and the docker compose file.
N/A
LUMI-28
=> Add documentation for environment variables in README and docker compose

lumigator/python/mzai/lm_buddy/requirements.txt, lumigator/python/mzai/sdk/BUILD.pants, lumigator/python/mzai/sdk/core.py, lumigator/python/mzai/sdk/healthcheck.py, lumigator/python/mzai/sdk/tests/BUILD.pants, lumigator/python/mzai/sdk/tests/test_sdk.py
=> Merge into sdk draft branch

PANTS_GUIDE.md
Small tweak in the `PANTS_GUIDE.md` doc when we mention 3rd-party (not as the file path).
=> README related tweak (`PANTS_GUIDE.md`)

lumigator/infra/mzai/helm/lumigator/templates/deployment.yaml
=> Fix up Env Vars for AWS Creds

lumigator/python/mzai/sdk/health.py
Small change: make the client member of `Health` 'private'.
=> make the client 'private'

lumigator/python/mzai/backend/backend/api/routes/completions.py, lumigator/python/mzai/sdk/client.py, lumigator/python/mzai/sdk/completions.py, lumigator/python/mzai/sdk/lumigator.py, lumigator/python/mzai/sdk/tests/conftest.py, lumigator/python/mzai/sdk/tests/test_completions.py
This PR adds support for the Completions API in the SDK.
Run the PyTest tests locally in your IDE, or `pants test lumigator/python/mzai/sdk:: -- -s`
=> SDK: Add 'Completions'

lumigator/python/mzai/backend/Dockerfile.uv
Adds a new dockerfile that works via UV
This allows for file upload, and works the summarizer via docker compose, but it does not work for eval just yet (will be done in a follow up PR)
=> Add docker backend

lumigator/python/mzai/backend/backend/tests/conftest.py
The test cases sometimes run into race conditions. Even though `pytest` itself is sequential, pants will run each test in parallel as shown [here](https://www.pantsbuild.org/dev/docs/python/goals/test). However, the only effect we have come across for the moment is an error creating the buckets, when the fixtures for different tests overlap. The fix focuses then on ignoring errors creating the buckets when the bucket already exists.
Just run the `pants` test.
-
=> Check test race conditions

CONTRIBUTING.md
=> Adding CONTRIBUTING

Makefile, lumigator/python/mzai/backend/backend/main.py, lumigator/python/mzai/sdk/README.md, lumigator/python/mzai/sdk/client.py, lumigator/python/mzai/sdk/completions.py, lumigator/python/mzai/sdk/lm_datasets.py, lumigator/python/mzai/sdk/lumigator.py, lumigator/python/mzai/sdk/tests/conftest.py, lumigator/python/mzai/sdk/tests/data/dataset.json, lumigator/python/mzai/sdk/tests/data/datasets.json, lumigator/python/mzai/sdk/tests/test_datasets.py, lumigator/python/mzai/sdk/tests/test_health.py
=> SDK: add `datasets`

lumigator/python/mzai/backend/pyproject.toml, lumigator/python/mzai/backend/uv.lock
Allows backend tests to be run via UV.
```
SQLALCHEMY_DATABASE_URL=sqlite:///local.db uv run pytest
```
=> Allow running of tests via uv

.github/workflows/tests_uv.yaml, lumigator/python/mzai/backend/pyproject.toml, lumigator/python/mzai/backend/uv.lock
=> Run backend tests in Github via UV

lumigator/python/mzai/backend/backend/tests/README.md
=> [LUMI-157] Update backend tests docs to remove pants and change to uv

.github/workflows/build_images_uv.yaml
=> Adding / fixing fmt and lint

Makefile, README.md
=> [LUMI-183] Make test

.github/workflows/build_images_uv.yaml
=> Adding ternary operator to tag latest only in main

lumigator/python/mzai/backend/backend/api/deps.py, lumigator/python/mzai/backend/backend/api/router.py, lumigator/python/mzai/backend/backend/api/routes/experiments.py, lumigator/python/mzai/backend/backend/tests/api/routes/test_api_workflows.py
`uvx ruff check --fix --config ruff.toml` found these required fixes/changes.
=> Linting: `uvx ruff check --fix --config ruff.toml`

Dockerfile, README.md
=> Comment fix

.gitignore
Addition to git ignore to prevent temporary journal files being committed. 
NA.
=> Git Ignore: Ignore temporary journal logs for SQLite

lumigator/python/mzai/backend/backend/api/deps.py
Removed duplicated line from deps.py
make test
=> Removed duplicated line from deps.py

README.md, docs/source/conceptual-guides/endpoints.md, docs/source/operations-guide/kubernetes.md
=> Docs: typo fix, and some styling/layout/links

lumigator/python/mzai/backend/backend/ray_submit/submission.py, lumigator/python/mzai/backend/backend/services/completions.py, lumigator/python/mzai/backend/backend/services/datasets.py, lumigator/python/mzai/backend/backend/services/jobs.py, lumigator/python/mzai/backend/backend/settings.py, lumigator/python/mzai/sdk/lumigator_sdk/lumigator.py, lumigator/python/mzai/sdk/tests/conftest.py, lumigator/python/mzai/sdk/tests/int_test_datasets.py, lumigator/python/mzai/sdk/tests/test_jobs.py
Ran `uvx ruff check --fix` on `main` and these changes appeared. 
Not sure how things seem to be slipping through via PRs 🤔
=> Linting: `uvx ruff check --fix` (again)

.github/workflows/test_sdk_uv.yaml, README.md
Fix badge links and change the test SDK workflow name for consistency.
=> Fix badge links and names

.github/labeler.yml
Extra labels added on PR's based on changes under certain directory paths in the repo.
=> GHA: add additional labels for PR labeler

lumigator/frontend/src/App.vue, lumigator/frontend/src/components/molecules/LExperimentForm.vue, lumigator/frontend/src/components/pages/LDatasets.vue, lumigator/frontend/src/services/experiments/experimentService.js, lumigator/frontend/src/stores/experiments/store.js
Notification Service with a toast panel in the bottom right corner.
- Delete a dataset
- Run an experiment
- Run a faulty experiment
To submit a faulty experiment you can comment out line 146 in `./frontend/src/components/molecules/LExperimentForm.vue`
=> Notification service

lumigator/python/mzai/sdk/lumigator_sdk/experiments.py, lumigator/python/mzai/sdk/lumigator_sdk/jobs.py, lumigator/python/mzai/sdk/lumigator_sdk/lm_datasets.py, lumigator/python/mzai/sdk/tests/integration/test_scenarios.py
For some reason pre-commit/linting seems to be missing files now and again and things creep into `main`.
`uvx ruff check --config ruff.toml --fix` ran on `main` and this is the resulting changeset.
=> Linting: uvx ruff check

.github/pull_request_template.md
Fixed a typo in the PR template.
- [NA] Tested the changes in a working envvironment to ensure they work as expected
- [NA] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)
=> chore: Fix typo in PR teplate

lumigator/frontend/src/App.vue, lumigator/frontend/src/components/organisms/LMenu.vue, lumigator/frontend/src/main.js
Add a tooltip informing user about current setup
=> tooltip for setup information

CONTRIBUTING.md
* Fixed bullet list in `CONTRIBUTING.md`.
- [NA] Tested the changes in a working environment to ensure they work as expected
- [NA] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)
=> chore: Fix bullet list in CONTRIBUTING.md

.github/workflows/build_and_push_sdk_packages.yaml
=> Changing to PyPI

.github/workflows/build_images_frontend.yaml, .github/workflows/build_images_uv.yaml, lumigator/python/mzai/schemas/pyproject.toml, lumigator/python/mzai/sdk/pyproject.toml
* Updated section...
* Added new...
* Removed outdated information from...
* Fixed a typo in...
* ...
Refs #...
Closes #...
1.
2.
3.
=> Publish PyPI packages and images with tags

.github/workflows/test_sdk_uv.yaml, lumigator/python/mzai/sdk/tests/data/dataset.json, lumigator/python/mzai/sdk/tests/data/datasets.json, lumigator/python/mzai/sdk/uv.lock
SDK tests seem broken due to schema changes. This PR addresses those tests, plus an additional check on schemas to fire the SDK tests.
Just check the CI actions.
N/A
- N/A
- N/A
- N/A
=> Fix SDK tests

.github/workflows/build_and_push_sdk_packages.yaml, tools/check_version.sh
Fix different bugs in the action in order to publish the SDK package
Try pipeline execution triggered by tag
N/A
=> Fixing errors in SDK pipeline

lumigator/python/mzai/sdk/lumigator_sdk/client.py, lumigator/python/mzai/sdk/lumigator_sdk/experiments.py, lumigator/python/mzai/sdk/lumigator_sdk/jobs.py, lumigator/python/mzai/sdk/lumigator_sdk/lm_datasets.py, lumigator/python/mzai/sdk/lumigator_sdk/models.py, lumigator/python/mzai/sdk/tests/unit/test_datasets.py, lumigator/python/mzai/sdk/tests/unit/test_jobs.py
Closes #488
Just run the SDK unit tests.
N/A
- N/A
=> SDK transparent error handling

lumigator/frontend/.env
I'm adding a `.env` file for the frontend.
Execute `make start-lumigator-build` and provide a dataset through the frontend.
N/A
=> Adding .env for frontend

lumigator/frontend/src/components/molecules/LExperimentDetails.vue, lumigator/frontend/src/components/molecules/LExperimentTable.vue, lumigator/frontend/src/services/experiments/experimentService.js, lumigator/frontend/src/services/health/healthService.js, lumigator/frontend/src/stores/experiments/store.js
An alternative option to https://github.com/mozilla-ai/lumigator/pull/541
This PR removes the running jobs and updates the experiments in the store instead.
1.
2.
3.
=> UI: Ensure (all) experiments which can have their status updated, get their status updated.

docker-compose.yaml
Docker compose will automatically assign the value to variables specified in the `environment` section if they're present. 
All tests will still pass (as their default values will be assigned etc.).
Some screenshots as receipts of how it works, looking at `RAY_HEAD_NODE_HOST`
=> Docker: Clean up docker compose

.github/workflows/lumigator_pipeline.yaml
Always build the backend image (useful for testing on kube and other platforms)
N/A
n/a
=> Build always BE

README.md, docker-compose.yaml, docs/source/get-started/installation.md, docs/source/get-started/quickstart.md, docs/source/index.rst, docs/source/operations-guide/dev.md, docs/source/user-guides/inference.md, lumigator/python/mzai/backend/README.md, lumigator/python/mzai/backend/backend/tests/conftest.py
- Removes references to minio from docs and some config files.
- Added reference to container in README
Closes #644
=> Removed references to minio, added frontend container

README.md, docs/source/get-started/installation.md
Wiki link was broken and apparently that github action doesn't run for Pull requests so it was missed in the last pr 🙈
=> Fix bad links in readme

lumigator/frontend/src/App.vue, lumigator/frontend/src/components/molecules/LModelCards.vue, lumigator/frontend/src/components/pages/LDatasets.vue, lumigator/frontend/src/services/datasets/datasetsService.js, lumigator/frontend/src/stores/datasets/store.js
When backend response with an error on a faulty dataset upload we propagate the error message to the UI
Resolves #509
=> Issue 509 dataset validation

lumigator/infra/mzai/helm/lumigator/charts/backend/values.yaml
Remove default resource requests for Ray (that should be set based on what cluster it's being deployed on)
=> Comment out default resource requests for Ray

README.md
1 letter in 2 env vars in the docs, so GPUs are enabled:
- [ NA] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)
- [NA ] Checked if a (backend) DB migration step was required and included it if required
=> fix(doc): RAY_WORKER_GPU*

.github/workflows/lumigator_pipeline.yaml
Changing tag regexp for pipeline
N/A
=> Changing tag regexp

lumigator/python/mzai/backend/uv.lock, lumigator/python/mzai/schemas/pyproject.toml, lumigator/python/mzai/sdk/pyproject.toml, lumigator/python/mzai/sdk/uv.lock
Changing version for the release
N/A
=> Changing version for the release

lumigator/python/mzai/backend/uv.lock, lumigator/python/mzai/schemas/pyproject.toml, lumigator/python/mzai/sdk/pyproject.toml, lumigator/python/mzai/sdk/uv.lock
=> Changing version

README.md
Currently our README doesn't tell anything about the helm installation of Lumigator
1.Read the readme and check the link
- [N/A ] Added some tests for any new functionality
- [N/A ] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)
- [ N/A] Checked if a (backend) DB migration step was required and included it if required
=> Adding helm chart link to the Readme

docs/source/get-started/installation.md, docs/source/operations-guide/kubernetes.md
=> docs fixes

.github/workflows/lumigator_pipeline.yaml, lumigator/backend/backend/tests/data/health_job_metadata.json, lumigator/backend/backend/tests/data/health_job_metadata_ray.json, lumigator/jobs/evaluator/requirements.txt, lumigator/jobs/evaluator_lite/requirements.txt, lumigator/sdk/tests/data/job-submit-resp.json, lumigator/sdk/tests/data/jobs-submit.json
Test PR for evaluate issues blocking the CI chain.
=> Fix for evaluate issues

docs/source/get-started/troubleshooting.md
* avaiable -> available
1.
2.
3.
=> docs: update troubleshooting.md

infra/helm/lumigator/charts/backend/values.yaml
Deleting not needed defaults in the Helm chart
Deploy the Helm chart
N/A
=> Deleting apiserver defaults

.github/workflows/lumigator_pipeline.yaml
I'm changing a condition in a step in the pipeline, due to that the changes not related with the code (non /lumigator ones), failed when PR was merged to main, ex: https://github.com/mozilla-ai/lumigator/actions/runs/13140574865/job/36666970370
N/A
N/A
=> Changing pipeline step condition

docs/source/index.rst
Adding the new S3 page to the documentation index
N/A
N/A
=> Adding new page to the index

lumigator/frontend/README.md, lumigator/frontend/src/components/molecules/LFileUpload.vue, lumigator/frontend/src/helpers/index.ts, lumigator/frontend/src/services/experiments/experimentService.ts, lumigator/frontend/src/stores/experiments/store.ts
Added some code comments from a leftover PR  https://github.com/mozilla-ai/lumigator/pull/786
=> docs: add code comments from #786 + hotfix for upload modal not going away

docs/source/reference/schemas.rst
Follow up fix for https://github.com/mozilla-ai/lumigator/pull/819
=> Remove completions referenced in docs

.pre-commit-config.yaml
=> Update dependencies used by pre-commit hooks

docker-compose.yaml, infra/helm/lumigator/Chart.yaml, infra/helm/lumigator/README.md, infra/helm/lumigator/charts/backend/Chart.yaml, infra/helm/lumigator/charts/backend/README.md, infra/helm/lumigator/charts/backend/values.yaml, infra/helm/lumigator/charts/frontend/Chart.yaml, infra/helm/lumigator/charts/frontend/README.md, infra/helm/lumigator/charts/frontend/values.yaml, lumigator/backend/pyproject.toml, lumigator/schemas/pyproject.toml, lumigator/sdk/pyproject.toml
Updating to v0.1.1-alpha to release the new version
N/A
=> Updating to v0.1.1-alpha

docs/source/conceptual-guides/datasets.md, docs/source/conceptual-guides/experiments.md, docs/source/conceptual-guides/jobs.md, docs/source/conceptual-guides/workflows.md, docs/source/index.rst
This is the first of a bunch of PRs for updating the documentation to be consistent with the current state of Lumigator. 
This PR adjusts the wording of the front page of the documents to point to the high level design of Lumigator and the main components. 
Refs #905
=> [DOCS] Update description on index page, add placeholder files for component concept guides

docs/source/user-guides/inference.md, docs/source/user-guides/local-models.md
When the LiteLLM PR was merged, this documentation was broken, since now an inference job must specify a provider. This PR fixes the documentation so that it should once again be runnable.
Refs #905 #956
=> Update the documentation for using a Local LLM

lumigator/jobs/inference/model_clients.py
In the LiteLLM PR I accidentally removed some logic via a bad merge. This PR puts it back 😬 
=> Put back HF text-generation support

Makefile, docs/source/operations-guide/configuration.md, scripts/common.sh, scripts/config_generate_env.sh, scripts/setup_uv.sh
* Refactored to remove logic from makefile
* `user.conf` now located under Lumigator dot directory for user (`~/.lumigator/user.conf`)
* Update `merge_conf_files` so it can be supplied numerous files of increasing priority for merging
1.
2.
3.
=> Scripts: refactor makefile + scripts for generating config and setting up uv

infra/helm/lumigator/charts/backend/templates/deployment.yaml, infra/helm/lumigator/charts/backend/values.yaml
Add lumigator secret key to helm chart
Refs #...
Closes #...
1.
2.
3.
=> Add lumigator secret key

infra/helm/lumigator/charts/frontend/templates/service.yaml, infra/helm/lumigator/charts/frontend/values.yaml
Add annotations for front end service
Refs #...
Closes #...
Set annotation for the front end service, you will see them reflected in the template
=> Add annotations for front end svc

lumigator/backend/backend/services/jobs.py, lumigator/backend/backend/services/workflows.py, lumigator/jobs/inference/model_clients.py, lumigator/jobs/inference/schemas.py, lumigator/jobs/inference/tests/data/config_full_api.json
This PR addressed the issue where the system_prompt parameter of the workflow create request was not being used during the inference request.
=> [BUG] System prompt unused

infra/helm/lumigator/charts/backend/templates/deployment.yaml
* Updated section...
* Added new...
* Removed outdated information from...
* Fixed a typo in...
* ...
Refs #...
Closes #...
1.
2.
3.
=> Fixing existingOpenaiAPISecret

lumigator/backend/backend/services/workflows.py
debug logging that shouldn't have made it into main.
Fixed an accidental extra log statement that was intended for debugging
=> Remove accidental log statement

cache/Dockerfile.model-inference
Small PR to fix pip mismatch issues
=> Ensure we have latest pip version to avoid hash mismatch

lumigator/backend/backend/services/jobs.py, lumigator/backend/backend/services/workflows.py
First step to improving the async run inference and eval function.
Added some more specific try/excepts for now. Previously some parts of the code called functions that threw exceptions that weren't handled, so the workflow just stayed as `CREATED`.
1. Try creating an experiment for OpenAI with no Open AI secret created (and no env vars in sight).
2. It should now at least show the experiment and workflows are failed (and there are errors in the backend logs)
=> Services: improve async error handling in run inference and eval

lumigator/backend/backend/models.yaml
* Updated section...
* Added new...
* Removed outdated information from...
* Fixed a typo in...
* ...
Refs #...
Closes #...
1.
2.
3.
=> Fix typo in models.yaml

lumigator/jobs/inference/tests/conftest.py, lumigator/jobs/inference/tests/test_generation_config_mixin.py
Fix fixture setup for loguru to capture output for test comparison. 
1.
2.
3.
=> fix logger adjustment in testing

lumigator/backend/backend/services/workflows.py, lumigator/backend/backend/tests/integration/api/routes/test_api_workflows.py, lumigator/backend/backend/tracking/mlflow.py, lumigator/jobs/evaluator/definition.py, lumigator/jobs/evaluator/evaluator.py, lumigator/jobs/inference/inference.py
Extracts S3 related code into functions for re-use and testing.
1.
2.
3.
=> Tracking client: extract S3 related tasks to functions

lumigator/backend/backend/tests/conftest.py, lumigator/backend/backend/tests/unit/tracking/test_mlflow.py, lumigator/backend/backend/tracking/mlflow.py
* Refactor compile metrics (change assertion to throw error)
* Add tests
* Fixes unrelated bug in delete job which was missing await
Refs: #1215
1.
2.
3.
=> Mlflow: refactor compile metrics method and add tests

lumigator/backend/backend/api/routes/workflows.py, lumigator/backend/backend/services/exceptions/tracking_exceptions.py, lumigator/backend/backend/services/exceptions/workflow_exceptions.py, lumigator/backend/backend/services/workflows.py, lumigator/backend/backend/tests/conftest.py, lumigator/backend/backend/tests/unit/tracking/test_mlflow.py, lumigator/backend/backend/tracking/mlflow.py
* Refactor `get_workflow` for workflow service and mlflow tracking client
* Refactor mlflow tracking client `get_job`
* Added more exceptions and exception handling (adds mapping at API layer for top level workflow upstream error)
* Added tests for `get_job`
Refs #1215 
1.
2.
3.
=> Refactor workflow service and mlflow tracking client

lumigator/backend/backend/tests/conftest.py, lumigator/backend/backend/tests/integration/api/routes/test_api_workflows.py
* Assert that the workflow didn't just complete, but succeeded.
* Update backend integration test code.
1.
2.
3.
=> Integration tests: Assert that the workflow that completed, succeeded

lumigator/backend/backend/tests/conftest.py, lumigator/backend/backend/tests/integration/api/routes/test_api_workflows.py
Update backend test code ...
* `wait_for_experiment` updated to match `wait_for_job`
* renamed some variables
* updated some method signatures with types
* added some doc strings
* modified the frequency and timeout for `wait_for_job` calls to be 5mins max and more regular checks (every 5secs)
* `run_workflow` doesn't bother setting 1000 sec job timeout only to overwrite it
1.
2.
3.
=> Update backend test code

.github/pull_request_template.md, .github/workflows/build_and_publish_docs.yaml, .gitignore, README.md, docs/source/conceptual-guides/architecture.md, docs/source/get-started/quickstart.md, docs/source/get-started/suggested-models.md, docs/source/get-started/ui-guide.md, docs/source/operations-guide/configuration.md, docs/source/user-guides/llm-as-judge.md, docs/source/user-guides/local-models.md, docs/source/user-guides/prepare-evaluation-dataset.md, lumigator/sdk/tests/integration/test_scenarios.py, lychee.toml, notebooks/README.md
* Skip integration test that is replicated in e2e
* Attempt to resolve issues with GHA docs link checker failing mainly on legit GitHub URLs (and preventing merges)
1.
2.
3.
=> Skip integration test that is behaving like an e2e test

README.md, docs/source/get-started/suggested-models.md
I'm adding a security advice in the README
N/A
N/A
=> Adding security advice
