.devcontainer/docker-compose-local.yaml
lumigator/python/mzai/backend/services/experiments.py
notebooks/README.md
notebooks/walkthrough.ipynb

Main change is the notebook itself. It now relies on dialogsum for the walkthrough.
A few days ago `datasets` deprecated the use of `use_auth_token` which now breaks our current code, this is fixed by freezing `datasets` version in lumigator (we can then update lm-buddy deps when the task of including it into lumigator is completed)
Run the notebook. Note that you'll need mistral api if you want to generate GT with it
https://mzai.atlassian.net/browse/LUMI-40

Added updated notebook and deps

---

.devcontainer/docker-compose-local.yaml
lumigator/infra/mzai/helm/lumigator/templates/deployment.yaml
lumigator/infra/mzai/helm/lumigator/values.yaml
lumigator/python/mzai/backend/settings.py

- Modified settings.py to support s3,coreweave and localstack:
Currently if `AWS_HOST` value is set to any string our settings.py will concatenate `AWS_HOST` and `AWS_PORT`. This concatenation is only required for localstack(afaik) so the change I propose is to make it explicit, because to use coreweave s3 storage we need to set AWS_HOST to a specific coreweave URL 
- Added Env Vars to the helm chart
- Download doesn't fully work, but it's related to a bug that's being worked on in [207](https://github.com/mozilla-ai/lumigator/pull/207) . I've checked that the URL is created with the right format for coreweave
- Currently S3_ENDPOINT_URL and AWS_ENDPOINT_URL. have the default same values, but they are used differently, one is passed onto ray and another one used to connect to s3 in …

[LUMI-19] Coreweave s3 support

---

lumigator/infra/mzai/helm/lumigator/Chart.yaml
lumigator/infra/mzai/helm/lumigator/templates/_helpers.tpl
lumigator/infra/mzai/helm/lumigator/templates/deployment.yaml

Chart values that are needed for the Deployment env vars should be made `required`, and show an error if they are null-valued (following the Go template definition).

[LUMI-21] Make required fields as `required` in chart

---

lumigator/python/mzai/backend/backend/jobs/submission.py
lumigator/python/mzai/backend/backend/services/experiments.py
lumigator/python/mzai/backend/schemas/jobs.py

Minor update to parametrize job submission. jobs/submission.py now gets a `command` parameter (string) and optional `args` (dictionary with k = --parameter_name and v = parameter_value) so it is possible to run jobs either by directly passing the command as a single string or just the base command + params (eventually everything becomes one string anyway at submission time but perhaps it saves a bit of hassle, especially if we decide to move back to structured configs and bring serialization into submission.py so developers won't have to be bothered by that).
curl directly hitting the API to run an experiment
https://mzai.atlassian.net/browse/LUMI-87

Parametrized job submission

---

.devcontainer/docker-compose-local.yaml
lumigator/python/mzai/backend/backend/services/experiments.py
lumigator/python/mzai/backend/backend/settings.py

This allows evaluator working_dir to be passed in dymanically based on different environments.
run `make local-up` and then run an evaluation, it should function as normal.

Make evaluator work dir configurable for different environments

---

.devcontainer/docker-compose-local.yaml
README.md
lumigator/python/mzai/backend/backend/settings.py
lumigator/python/mzai/sdk/tests/data/job.json
lumigator/python/mzai/sdk/tests/data/jobs.json

Set secrets directly on Ray node instead of via backend (secrets passed via env var of ray jobs api are leaked in the logs, etc) 
Other minor changes:
- AWS_HOST doesn't seem to be set anywhere anymore, so remove from docs,
- Set HF_TOKEN on directly on ray workers now
- Remove setting LOCAL_FSSPEC_S3 env vars on the backend side (only needed by the evaluate ray job)
- Remove secrets from mocks
Run `make local-up`
https://mzai.atlassian.net/browse/LUMI-53

LUMI-53   [Security] Remove secrets from RAY_WORKER_ENV_VARS

---

.gitignore
lumigator/python/mzai/backend/schemas/experiments.py
lumigator/python/mzai/sdk/experiments.py
lumigator/python/mzai/sdk/lumigator.py
lumigator/python/mzai/sdk/tests/BUILD.pants
lumigator/python/mzai/sdk/tests/conftest.py
lumigator/python/mzai/sdk/tests/data/experiment-download-no-experiment.json
lumigator/python/mzai/sdk/tests/data/experiment-download.json
lumigator/python/mzai/sdk/tests/data/experiment-missing.json
lumigator/python/mzai/sdk/tests/data/experiment-post-all.json
lumigator/python/mzai/sdk/tests/data/experiment-post-response.json
lumigator/python/mzai/sdk/tests/data/experiment-post-simple.json
lumigator/python/mzai/sdk/tests/data/experiment-result-no-experiment.json
lumigator/python/mzai/sdk/tests/data/experiment-result.json
lumigator/python/mzai/sdk/tests/data/experiment.json
lumigator/python/mzai/sdk/tests/data/experiments.json
lumigator/python/mzai/sdk/tests/helpers.py
lumigator/python/mzai/sdk/tests/test_experiments.py

This PR adds support for the Experiments API in the SDK.
Run the PyTest tests locally in your IDE, or `pants test lumigator/python/mzai/sdk:: -- -s`

SDK: Add 'experiments'

---

lumigator/python/mzai/backend/backend/records/datasets.py
lumigator/python/mzai/backend/backend/services/datasets.py
lumigator/python/mzai/backend/backend/tests/api/routes/test_datasets.py
lumigator/python/mzai/backend/schemas/datasets.py
lumigator/python/mzai/sdk/tests/data/dataset.json
lumigator/python/mzai/sdk/tests/data/datasets.json
lumigator/python/mzai/sdk/tests/test_datasets.py

A new field is added to the datasets table recording whether GT is included within a dataset.
Exposing this information allows the UI to act accordingly (e.g. warning the user before running an eval) without downloading the whole dataset.
- unit tests: pants test lumigator/python/mzai/backend/backend/tests:backend_tests@parametrize=darwin
- integration tests w curl
https://mzai.atlassian.net/browse/LUMI-88
I added @peteski22 and @javiermtorres to get specific SDK-related feedback 🙏 
- [ x] added some tests for any new functionality: UNIT TEST

Added GT field recording whether a dataset contains GT

---

.devcontainer/docker-compose.override.yaml
Makefile
docker-compose.yaml

This adds to ability to build the docker images for backend to the main docker compose file

Add option to build to main docker-compose file and add make target

---

.github/workflows/sdk_integration_tests.yaml
lumigator/python/mzai/sdk/BUILD.pants
lumigator/python/mzai/sdk/tests/BUILD.pants
lumigator/python/mzai/sdk/tests/conftest.py
lumigator/python/mzai/sdk/tests/data/dialogsum_exc.csv
lumigator/python/mzai/sdk/tests/int_test_datasets.py
lumigator/python/mzai/sdk/tests/test_datasets.py

Integration tests will check against a running Lumigator instead of mocking responses.
A separate test with address `lumigator/python/mzai/sdk/tests/int_test_datasets.py:sdk_tests` has been provided.
LUMI-136

Add integration tests

---

.github/workflows/sdk_integration_tests.yaml
.github/workflows/tests_uv.yaml

This runs both integration test suites against the _current_ code. Not the `latest` tag (which currently represents the `latest` code built, and as such could literally be any branch)
Run pytest in backend and sdk projects

[ LUMI-184] Build lumigator before tests

---

lumigator/python/mzai/backend/backend/services/datasets.py
lumigator/python/mzai/backend/backend/tests/api/routes/test_api_workflows.py
lumigator/python/mzai/backend/backend/tests/api/routes/test_datasets.py
lumigator/python/mzai/schemas/schemas/datasets.py
lumigator/python/mzai/sdk/sdk/lm_datasets.py
lumigator/python/mzai/sdk/tests/data/dataset.json
lumigator/python/mzai/sdk/tests/data/datasets.json
lumigator/python/mzai/sdk/tests/int_test_datasets.py
lumigator/python/mzai/sdk/tests/test_datasets.py

Addressing https://github.com/mozilla-ai/lumigator/issues/144 - We'd like to only require `examples` as a field and allow for optional fields, including `ground_truth` so we don't create errors when users upload data with more fields or files from other experiments.  Also changing `EXPERIMENT` to `JOB` for dataset format validation.  
Unit tests and upload file with various headers

Change dataset input fields to required only 

---

Makefile
README.md

stop-lumigator is now called inside make test, to clean up.
Clean folder, clone, docker ps shows no (lumigator-related) running containers, make test, docker ps shows no running containers (lumigator-related) and no unrelated containers were stopped.
We could discuss tearing down only those started by make test, but hopefully this is already better than not tearing down lumigator containers after the test.
Pre-commit hooks also fixed some whitespaces in the Makefile.

chore: tear down containers launched after make test

---

lumigator/python/mzai/backend/backend/api/routes/datasets.py
lumigator/python/mzai/backend/backend/services/datasets.py
lumigator/python/mzai/backend/backend/tests/api/routes/test_datasets.py
lumigator/python/mzai/backend/backend/tests/conftest.py
lumigator/python/mzai/backend/backend/tests/services/test_dataset_service.py

When attempting to delete a dataset which encounters issues, we now do the following:
* If the dataset existed in the DB but the file wasn't found in S3, we remove it from the DB
* Any other errors in the service will raise an exception (non-HTTP)
* The route/controller handles any exceptions, logging them and returning a 500 to the caller (with a generic message)

Datasets: deleting a dataset with a DB entry but no S3 file should be handled correctly

---

.github/workflows/build_images_uv.yaml

We currently have an [issue](https://github.com/mozilla-ai/lumigator/issues/343) when external users want to open a PR against our code. This is related to [accessing](https://michaelheap.com/access-secrets-from-forks/) secrets from forks. The proposed solution is to only login & push to dockerhub when we actually merge to main (as I don't think we need the images in dockerhub if they come from a PR)
We've also removed the linting process from the PR/push to main as it's already triggered every time we [push](https://github.com/mozilla-ai/lumigator/blob/main/.github/workflows/tests_uv.yaml)
Ensure CI works properly and after merge we can fork the repo and try to see if the error still happens
- [N/A] added some tests for any new functionality
- [N/A] updated the documentation
- [N/A] …

Trigger push to dockerhub only when merging PRs

---

.github/workflows/notebook_integration_tests.yaml

The notebook integration test should only run if code is merged into main or if a new PR is opened. Currently, it also runs if a new branch named `fix-**` is pushed, due to legacy behavior.
Remove the rule that triggers the test when a new `fix-**` is pushed.

workflows: Amend Notebook integration test

---

.github/workflows/build_images_uv.yaml
.github/workflows/docs.yaml
.github/workflows/links_checker.yaml
.github/workflows/sdk_integration_tests.yaml
.github/workflows/tests_uv.yaml
.github/workflows/tests_uv_sdk.yaml

GitHub's UI can make it difficult to know for sure which task you're trying  to associate with a required status check as it resolves only the job name and shows no information about the scope (i.e. the workflow name it is associate with).
This PR makes the job names more specific as to which workflow they are part of.
Once the PR merges it will be easier to find and [configure the required status checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-status-checks-before-merging) for PRs merging to `main`.
Current branch protection rules for main only have a few checks configured, but we'd want more to be successful before allowing a merge. 
This way we can ensure that we don't …

GHA: Update names of workflow jobs

---

.github/workflows/tests_uv.yaml
.github/workflows/tests_uv_sdk.yaml

Some required checks may hang when the branch of a PR is updated via GitHub's UI (merges `main`) as this doesn't retrigger the workflow job. 
This PR modifies the `on` for SDK and backend tests.

run tests (SDK/Backend) on PR changes and when PRs merge to main

---

lumigator/python/mzai/backend/backend/services/jobs.py
lumigator/python/mzai/backend/backend/tests/conftest.py
lumigator/python/mzai/backend/backend/tests/fakes/fake_ray_client.py
lumigator/python/mzai/backend/backend/tests/services/test_job_service.py
lumigator/python/mzai/jobs/evaluator/evaluator/configs/jobs/hf_evaluate.py
lumigator/python/mzai/jobs/inference/inference_config.py
lumigator/python/mzai/schemas/lumigator_schemas/experiments.py
lumigator/python/mzai/schemas/lumigator_schemas/jobs.py

We're currently not enforcing a `max_samples` value when they initially get passed into the application, and then again when they're sent via the API to Ray. 
This forces `max_samples` for both inference and eval jobs to be set if they're not once on input and once again on submission for evaluation.  Tests cover setting via the service. 
Original PR was here, overwritten by improvements/merges from inference API. (https://github.com/mozilla-ai/lumigator/compare/main...fix_max_samples)
Unit tests cover input at the API level.

Set max samples to unlimited by default with option to override API request cycle

---

lumigator/python/mzai/backend/backend/api/routes/health.py
lumigator/python/mzai/backend/backend/settings.py
lumigator/python/mzai/backend/backend/tests/api/routes/test_datasets.py
lumigator/python/mzai/backend/backend/tests/api/routes/test_health.py
lumigator/python/mzai/backend/backend/tests/conftest.py
lumigator/python/mzai/backend/backend/tests/fakes/fake_ray_client.py
lumigator/python/mzai/backend/backend/tests/services/test_job_service.py
lumigator/python/mzai/jobs/evaluator/evaluator/paths.py
lumigator/python/mzai/schemas/lumigator_schemas/jobs.py

Added a new endpoint (`/health/jobs/{job_id}/logs`) which connects to the local [ray server API](https://docs.ray.io/en/latest/cluster/running-applications/job-submission/rest.html) (on `/api/jobs/{job_id}/logs`) to get logs given a job id.
This could be used to surface logs to a UI / SDK / generic client both at the end of the job and when it is running (by polling our API).
- start a job
- send a request to the `/health/jobs/{job_id}/logs` API endpoint (e.g. from the http://localhost:8000/docs# interface)
N/A

Adding job logs support to health endpoint [LUMI-211]

---

.github/workflows/build_images_uv.yaml

The `Docker image CI` workflow can be run on merges to `main` and PR branches. It is required as a status check before allowing a merge to occur, but there are times when we don't need to rebuild the image, for example if only the `/docs` folder changes in a PR it's a waste of time and resources to build the docker image. 
With this PR change we will always trigger the workflow, but it can successfully 'exit early' if a rebuild is not required.
The current folders that are examined for changes are:
* `.github/**`
* `lumigator/**`
We use [dorny/paths-filter](https://github.com/dorny/paths-filter) to do the heavy lifting/checking for us, previous iterations of this PR tried to do a lot of juggling with `git diff `and `git diff-tree` etc.
The [GH runner …

GitHub actions: allow docker image build to be a required check

---

.github/workflows/build_and_publish_docs.yaml
.github/workflows/check_links.yaml

Link checking needs to happen regardless as it scans the whole repo for file changes (such as on `.md`s) not just `/docs`.
When link checking completes it should trigger the docs building workflow (as it did previously). 
NOTE: the workflow that is the trigger needs to exist in `main` (the default branch) in order for this to work.
See: https://github.com/mozilla-ai/lumigator/pull/394

GitHub actions: update link checker and docs build workflows

---

.github/workflows/test_sdk_uv.yaml

The `SDK unit tests - Python` job will still be triggered but will be able to exit early, and successfully if there are no changes to the sdk folder.
NOTE: Integration tests cannot be skipped using this rule as changes elsewhere in the code base need to be assured in the SDK too.
https://github.com/mozilla-ai/lumigator/actions/runs/11935459789/job/33266824892?pr=402#step:3:17

GHA: SDK - run unit tests only when there are changes to SDK

---

.github/workflows/test_notebook_integration.yaml
lumigator/python/mzai/sdk/README.md
notebooks/requirements.txt

The documentation and notebooks assume we are already automatically pushing to PyPI. This is not the case, which caused this bug for a user.
This PR updates notebook requirements.txt and updates the documentation while we are changing the automatic versioning and publishing.
* Follow the instructions to run the notebook here.
* Run the imports cell.
* Before this PR, it would fail, as the schemas and SDK were not installed. It should now return no errors.
This is a temporary fix, since the underlying problem is not being able to do pip install lumigator-sdk, but at least we won't block folks trying Lumigator.
- [N/A] added some tests for any new functionality

410 notebook and documentation instructions to install schemas and sdk assume pypi

---

lumigator/frontend/Dockerfile
lumigator/frontend/nginx.conf

Our frontend operates as a single page application (SPA), and we create a container to host it using nginx when we `make local-up` or `make start-build-lumigator`.
When using the app, the URL bar appears to show different paths (`/datasets`, `/experiments`) but they're all hosted from the same place. However, nginx doesn't know this and so if you attempt to browse directly to a page (rather than the root), or refresh a page you get a 404 not found.
This PR changes the default nginx daemon config so that it will reroute requests to the root index page. In order to add the single line:
```
try_files $uri $uri/ /index.html;
```
We need to supply the entire config file, as such we now have a copy of the `default.conf` modified that is copied by Docker.
* `make start-lumigator-build`
* …

Frontend: support single page apps (SPA) when served with nginx

---

docs/source/conf.py
docs/source/get-started/suggested-models.md
docs/source/index.rst
docs/source/reference/schemas.rst
docs/source/reference/sdk.rst
lumigator/python/mzai/backend/backend/api/router.py
lumigator/python/mzai/backend/backend/api/routes/models.py
lumigator/python/mzai/backend/backend/api/tags.py
lumigator/python/mzai/backend/backend/models.yaml
lumigator/python/mzai/backend/backend/tests/api/routes/test_models.py
lumigator/python/mzai/backend/backend/tests/conftest.py
lumigator/python/mzai/backend/backend/tests/data/models.json
lumigator/python/mzai/schemas/lumigator_schemas/models.py
lumigator/python/mzai/sdk/lumigator_sdk/lumigator.py
lumigator/python/mzai/sdk/lumigator_sdk/models.py
lumigator/python/mzai/sdk/tests/conftest.py
lumigator/python/mzai/sdk/tests/data/models.json
lumigator/python/mzai/sdk/tests/test_models.py

This PR introduces a new `/models` endpoint that returns a list of suggested models for a given task. Currently, the only supported task is "summarization."
The suggested models are stored in a YAML file, along with details such as number of parameters, memory footprint, and default values. Not all information is available for every model. For example, OpenAI models do not provide memory footprint data, while other models may not include summarization-specific default parameters.
Additionally, this PR adds a new SDK function for calling the `/models` endpoint via Python, along with the corresponding documentation.
1. Run a local Lumigator deployment: `make local-up`
1. Run the following command:
```bash
curl -s http://localhost:8000/api/v1/models/summarization | jq
```
If you request the …

[backend] Expose suggested models

---

.dockerignore
docker-compose.yaml
lumigator/frontend/Dockerfile

When running from a clean clone of the repository, the frontend container is deployed, but is missing environment variables to during the multi stage build process to configure the API URL (`VUE_APP_BASE_URL`).
Reasons for this appear to be:
1. The `.env` file in the root of the repository is ignored by the `.dockerignore` value: `.env/` which was designed to prevent virtual environment folders being uploaded. This means it is not copied to the `/mzai/` WORKDIR.
2. The build system expects the `.env` file to be present locally within the `/frontend` folder.
~This PR allows Docker to copy the `.env` file to the intermediate 'build' stage (by modifying the `.dockerignore` file), and then copies the frontend specific variables to a new (temporary) `.env` file in the `/frontend` folder.~
This …

Frontend: ensure .env file is available to container during build

---

.github/workflows/test_backend_uv.yaml
.github/workflows/test_sdk_integration.yaml
.github/workflows/test_sdk_uv.yaml
Makefile

Currently, running `make test` has the following consequences:
* Containers are started, ignoring any container that is already running.
* If everything works, all containers are teared down including those started with `make local-up`.
* If anything breaks during tests, `make stop-lumigator` is not run and the containers stay up.
Transform the `make test` target to check whether there are already running containers before starting tests:
- If so, simply run tests.
- If not: (1) start containers, (2) run tests, (3) tear down containers (regardless of tests outcome).
1. Run `make local-up`.
1. Run `make test` in another window.
1. If the tests complete successfully, all the containers started with `make local-up` should remain running.
1. Run `make stop-lumigator`.
1. Run `make test`. New …

makefile: Run tests without altering state

---

lumigator/frontend/src/components/pages/LExperiments.vue

This is a bug fix. When the user is switching from one experiment' results to another's the table component doesn't update it contents.
1. Open results for an experiment
2. Close results panel
3. Open results for another one with different number of samples

Fix results caching

---

Makefile

`start-lumigator-build` already uses the `local-fe` profile, this PR adds it to `start-lumigator` too.
`stop-lumigator` uses the same profile to shutdown the containers.
* `make start-lumigator`
* Should see the frontend container deployed alongside everything else

Deployment: Add frontend profile to `start-lumigator`

---

.github/workflows/build_images_frontend.yaml

The GHA for the frontend container uses the dorny paths-filter to decide if all the steps are required, but when running against `main` the [GHA failed](https://github.com/mozilla-ai/lumigator/actions/runs/12070875284/job/33661341581).
This PR adds the checkout action before the paths filters are used to ensure we have the latest code pulled in.
Related PR: https://github.com/mozilla-ai/lumigator/pull/418
1.
2.
3.

Frontend: GHA tweak to add checkout action before checking for path changes

---

lumigator/python/mzai/backend/backend/services/jobs.py
lumigator/python/mzai/backend/backend/settings.py
lumigator/python/mzai/backend/backend/tests/conftest.py
lumigator/python/mzai/backend/backend/tests/data/ray_version.json
lumigator/python/mzai/backend/backend/tests/unit/api/routes/test_jobs.py
lumigator/python/mzai/schemas/lumigator_schemas/jobs.py

The `/jobs` endpoint can return the status of a specific Ray job, but this status is not updated beyond "created".
Optionally refresh the database record before returning:
* Immediately return statuses "Succeeded" and "Failed" because they cannot change.
* Otherwise, consult Ray first, and if the status differs from the one in the DB, update the DB and return the updated record.
Closes #382
1. Upload a dataset
1. Launch a job (e.g. evaluation with BART)
1. List jobs, find the job_id of one (e.g., the one you just created)
1. GET /jobs/{job_id} --> created
1. Check on the ray dashboard until that job has finished
1. GET /jobs/{job_id} --> finished
- [NA] updated the documentation
- [NA] checked if a (backend) DB migration step was required and included it if required

backend: Refresh job status

---

.devcontainer/docker-compose.override.yaml

While automatic backend reloads are useful for testing code changes in real-time, the backend should not be impacted by updates in unrelated subdirectories (e.g., running `uv venv` in notebooks).
Update the docker-compose override file to watch only the directories relevant to the backend.
Closes #432
1. Run `make local-up`
2. Navigate into `notebooks`:
```
cd notebooks
```
3. Run `uv venv` to create a new uv virtual environment. Docker should not detect any change.
4. Change somethin in a `.py` file in the `backend`. Docker should detect the change and sync the backend container. 
- [NA] added some tests for any new functionality
- [NA] updated the documentation
- [NA] checked if a (backend) DB migration step was required and included it if required

[BUG] Limit auto-reload to relevant directories

---

CONTRIBUTING.md

Closes #439 . Pre-MVP phase (i.e. no feature PRs).
- [NA] added some tests for any new functionality
- [NA] checked if a (backend) DB migration step was required and included it if required

Update contributing.md (pre-MVP phase)

---

lumigator/python/mzai/backend/backend/config_templates.py
lumigator/python/mzai/backend/backend/services/jobs.py
lumigator/python/mzai/jobs/evaluator/evaluator/configs/jobs/hf_evaluate.py
lumigator/python/mzai/jobs/evaluator/evaluator/jobs/asset_loader.py
lumigator/python/mzai/jobs/evaluator/evaluator/jobs/evaluation/lm_harness.py
lumigator/python/mzai/jobs/evaluator/evaluator/paths.py
lumigator/python/mzai/jobs/inference/inference.py
lumigator/python/mzai/jobs/inference/inference_config.py
lumigator/python/mzai/jobs/inference/tests/data/config_full_hf.json
lumigator/python/mzai/jobs/inference/tests/test_configs.py
lumigator/python/mzai/sdk/tests/conftest.py

In the codebase, we currently name terms like `hf://...` as "model paths" and "URIs." This inconsistency can cause confusion and make the code harder to read and maintain.
Refactor `model_path` to `model_uri`.
Closes #428
- - [x] Tested the changes in a working environment to ensure they work as expected
- [NA] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)

Refactor `model_path` to `model_uri`

---

Makefile
docker-compose.yaml

I've removed the local-fe profile from `docker-compose.yml` and our` Makefile` to ensure the frontend always starts. 
With this change, local-up, start-lumigator, start-lumigator-external-services will all start the frontend service pulling the latest image.
In a follow up PR I aim to create a different version for the `local-up` make target, as `local-up` should be a contributor mode (starting a dev container with npm run serve, instead of an nginx with the code already built)
Ensure all make targets that spin the environment start the Frontend, and all make targets that stop the environment stop the frontend container.
- [N/A ] Added some tests for any new functionality
- [N/A] Updated the documentation (both comments in code and [product …

Ensure Frontend service starts with Make

---

lumigator/python/mzai/sdk/pyproject.toml
lumigator/python/mzai/sdk/tests/conftest.py
lumigator/python/mzai/sdk/tests/integration/test_scenarios.py
lumigator/python/mzai/sdk/tests/unit/test_completions.py
lumigator/python/mzai/sdk/tests/unit/test_datasets.py
lumigator/python/mzai/sdk/tests/unit/test_health.py
lumigator/python/mzai/sdk/tests/unit/test_jobs.py
lumigator/python/mzai/sdk/tests/unit/test_models.py
lumigator/python/mzai/sdk/uv.lock

The `requests-mock` package has been retrofitted to the existing SDK tests, as a prerequisite to #488.
The automated tests should run ok.
This package makes it easier to understand how to mock HTTP requests.

Retrofit requests-mock in SDK

---

lumigator/frontend/src/components/molecules/LExperimentDetails.vue
lumigator/frontend/src/styles/_lumigator-theme.scss

Experiments that have failed do not yield an endpoint to fetch their results which leads to unwanted behavior when users click the _"Show results"_ button.

Disable results btn on failed experiments

---

docs/source/get-started/quickstart.md
lumigator/python/mzai/backend/backend/ray_submit/submission.py
lumigator/python/mzai/backend/backend/services/jobs.py
lumigator/python/mzai/backend/backend/settings.py
lumigator/python/mzai/backend/backend/tests/data/health_job_metadata.json
lumigator/python/mzai/backend/backend/tests/data/health_job_metadata_ray.json
lumigator/python/mzai/backend/backend/tests/unit/api/routes/test_jobs.py
lumigator/python/mzai/jobs/evaluator/evaluator/jobs/evaluation/hf_evaluate.py
lumigator/python/mzai/jobs/evaluator/examples/configs/evaluation/hf_evaluate_config.yaml
lumigator/python/mzai/jobs/evaluator/examples/configs/evaluation/hf_evaluate_inference_server_config.yaml
lumigator/python/mzai/jobs/evaluator/examples/configs/evaluation/hf_evaluate_openai_config.yaml

When an inference or evaluation job completes successfully, it creates a results file and stores it in object storage. The file is named either `eval_results.json` or `inference_results.json`, depending on the job type.
However, when attempting to generate a download URL through `/api/v1/jobs/{job_id}/result/download`, the URL always points to a file named eval_results.json. For inference jobs, this file does not exist, resulting in a broken download process.
Dynamically assign the file name based on the job type.
Also, change `eval_results` to `evaluation_results` for uniformity.
Closes #503
Steps to Reproduce:
1. Run an inference job to completion.
1. Check the S3 URI that points to the results file. The file name is `inference_results.json`.
1. Try to download the file, by retrieving a …

Fix job's results file name

---

docs/source/user-guides/inference.md
lumigator/python/mzai/jobs/inference/inference.py

Change the inference job's results file name to `results.json`.
Refs #503
- - [x] Tested the changes in a working environment to ensure they work as expected
- - [x] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)

Change inference job's results file name

---

.github/workflows/build_images_frontend.yaml

Fixing naming bug for frontend images generated when a PR is merged to main
Take a look to the action that builds the FE
e.g. 
commit: `e9408ee1e393824b3b8799e6dab1e6d2d86c6011`
shortened: `e9408ee`
https://github.com/mozilla-ai/lumigator/actions/runs/12432909639/job/34713333184?pr=545#step:4:2
```
echo "GITHUB_SHA_SHORT=$(echo e9408ee1e393824b3b8799e6dab1e6d2d86c6011 | cut -c1-7)" >> $GITHUB_ENV
```
https://github.com/mozilla-ai/lumigator/actions/runs/12432909639/job/34713333184?pr=545#step:6:6
```
Run docker/build-push-action@v6
with:
file: lumigator/frontend/Dockerfile
push: false
target: server
tags: mzdotai/lumigator-frontend:frontend_e9408ee
load: false
no-cache: false
pull: false
github-token: ***
env:
GITHUB_SHA_SHORT: e9408ee
```
N/A

Fix FE build and push

---

Makefile
docs/source/get-started/suggested-models.md
lumigator/python/mzai/backend/backend/api/routes/jobs.py
lumigator/python/mzai/backend/backend/tests/integration/api/routes/test_api_workflows.py
lumigator/python/mzai/schemas/lumigator_schemas/jobs.py

Lumigator used to offer a service, /groundtruth, to annotate a dataset when it did not have human-provided ground-truth to compare against in evaluation. This PR does not address whether this is a good practice; inference marks its results as AI-generated (with the field "model: ai_model_that_generated_them" as an output attribute). The user can use this information to trust accordingly.
* Adds annotation using the new, independent inference job with a model selected by us (bart).
* Exposes the service as /jobs/annotate
* Introduces JobAnnotationCreate, which does not allow setting model or temperature. It hands over to a JobInferenceCreate which sets the model and temperature we decided. 
Closes #337 
1. Start lumigator (make local-up or start-lumigator build) …

337 annotation/ground truth generation uses new inference job

---

.env.example
.github/workflows/test_backend_uv.yaml
Makefile
lumigator/python/mzai/backend/README.md
lumigator/python/mzai/backend/backend/config_templates.py
lumigator/python/mzai/backend/backend/services/datasets.py
lumigator/python/mzai/backend/backend/services/jobs.py
lumigator/python/mzai/backend/backend/tests/README.md
lumigator/python/mzai/backend/backend/tests/conftest.py
lumigator/python/mzai/backend/backend/tests/fakes/fake_ray_client.py
lumigator/python/mzai/backend/backend/tests/fakes/fake_s3.py
lumigator/python/mzai/backend/backend/tests/integration/api/routes/test_api_workflows.py
lumigator/python/mzai/backend/backend/tests/unit/api/routes/test_datasets.py
lumigator/python/mzai/backend/backend/tests/unit/api/routes/test_jobs.py
lumigator/python/mzai/backend/backend/tests/unit/services/test_dataset_service.py
lumigator/python/mzai/jobs/inference/requirements_cpu.txt
lumigator/python/mzai/sdk/lumigator_sdk/client.py
lumigator/python/mzai/sdk/lumigator_sdk/experiments.py
lumigator/python/mzai/sdk/tests/integration/test_scenarios.py

Unit tests in the backend can benefit from a BytesIO/StringIO backed fake S3, with both FakeS3Client and FakeS3FS. Integration tests will use an existing localstack, if any.
The previously used localstack started by testcontainers has been removed.
Just run the unit tests without the auxiiliary containers, and run the integration tests with the auxiliary containers.
Fixes https://github.com/mozilla-ai/lumigator/issues/422
- Not needed since this is a test improvement.

Add fakes for the S3 service and use the standalone localstack

---

.env.example
Makefile

The `KEEP_CONTAINERS_UP` env var did not work correctly.
With the default config in `main`, use `make test-sdk-integration`. The containers will not stop after tests.
N/A

Hotfix for container stop in tests

---

Makefile

Currently our Makefile includes the `.env` file to pull `KEEP_CONTAINERS_UP="FALSE" variable into the Makefile. That's causing issues because the way our variables are defined in the `.env` file. In this PR I remove the include and just pull the var in the Makefile to avoid general issues.
1. You can still use the Make targets for the SDK/Backend tests with the containers running while all the Vars are as they are in the `.env` file inside the containers
- [N/A ] Added some tests for any new functionality
- [N/A] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)
- [N/A ] Checked if a (backend) …

Remove global include from Makefile

---

lumigator/frontend/src/components/molecules/LExperimentForm.vue
lumigator/frontend/src/components/molecules/LModelCards.vue
lumigator/frontend/src/components/pages/LExperiments.vue
lumigator/frontend/src/services/models/api.js
lumigator/frontend/src/services/models/modelsService.js
lumigator/frontend/src/stores/models/store.js

We use the `/models/{task_name}` endpoint to populate the list of models inside the experiment form
Refs #...
Closes #556 
Try to run a new experiment 
⚠️ Some of the new model options require an API key ⚠️ 
If the Lumigator operator hasn't configured the specific API key during setup, Lumigator won't be able to contact the API for the model successfully.
Currently there is no warning about this as the UI has no way to know:
1. If the API requires an API key
1. If Lumigator has the key configured or not
As a result, the experiment/job is registered in the backend but soon after receives a "Failed" status. The user will likely only notice the misconfiguration by examining the logs. 
> The link to the documentation website of each model is missing because it's not provided from the API. …

Issue 556 retrieve models

---

lumigator/python/mzai/backend/backend/models.yaml
lumigator/python/mzai/schemas/lumigator_schemas/models.py
lumigator/python/mzai/sdk/tests/data/models.json

API responses for summarization models now include a link to the model (where possible), most models have a unique link but some mistral ones all appear on their website with the same URL.
Name `website_url` can be easily changed if required, thought about `model_card` but since some aren't exactly 'that' I just went for slightly more vague.
Refs https://github.com/mozilla-ai/lumigator/issues/589
1. Visit the [API docs for models](http://localhost:8000/docs#/models/get_suggested_models_api_v1_models__task_name__get)
1. 'Try it out' for `summarization` 
1. Check the URL is being shown for each model

API:include URL to website for models

---

lumigator/frontend/src/components/molecules/LModelCards.vue

- `models/` endpoint was updated and now provides links for every model's website. Therefore the link in the UI is restored.
- UX improvement: enable user to select model not only by clicking on the radio button explicitly but anywhere on model's card
1. Open form for a new experiment
2. At _"select model"_ section of the form click on the right icon of each card.
3. Select a model by clicking on card's label (text).

Restoring models' website urls

---

lumigator/python/mzai/backend/backend/models.yaml

Remove `/discussions` from the end of the URL as it shouldn't be there.

Fix: API website URL for model update

---

.github/workflows/build_images_frontend.yaml

This builds and pushes the frontend during PRs and not just on pushes to main or tag releases. This allows for easier testing on kubernetes and other platforms by giving a consistent and accessible container image.
N/A
This does not change our rules around running workflows for external contributors, who will still require approval before running workflows.

Push frontend to dockerhub in more cases

---

lumigator/python/mzai/backend/backend/api/routes/datasets.py
lumigator/python/mzai/backend/backend/services/experiments.py

Small PR to fix typos in API documentation.
2. Go to the API docs [upload dataset](http://localhost:8000/docs#/datasets/upload_dataset_api_v1_datasets__post)
3. Check documentation

Update typos in API docs

---

docs/source/get-started/suggested-models.md

The suggested models returned by the Lumigator API are models that users can evaluate on their own datasets. However, other models can be used under the hood, such as `roberta-large` to calculate the BERTScore.
Clarify the scope and usage of the suggested models returned by the Lumigator API.
Closes #359
- [NA] Tested the changes in a working environment to ensure they work as expected
- - [x] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)

docs: Clarify suggested models scope and usage

---

docker-compose.yaml

Would it be ok if we check the health more often? My minio stack is normally up after ~7 seconds so this change would save me about 20 seconds every time I run local-up. I kept the same total duration by bumping up the retries.
1.`make local-up`
- [ x] Tested the changes in a working environment to ensure they work as expected
- [x ] Checked if a (backend) DB migration step was required and included it if required

Check Minio health more often

---

.env.example
.github/workflows/lumigator_pipeline.yaml
docker-compose.yaml
docs/source/operations-guide/dev.md
lumigator/frontend/Dockerfile
lumigator/frontend/src/services/http/index.js

This changes the front end from having a hard coded path to the backend to accessing the backend on a path relative to the backend
Before
```
baseURL: 'http://my-backend-domain:8000/api/v1'
```
After
```
baseURL: '/api/v1'
```
This worked before, since with docker compose, the front end build occurs just before runtime, and `VUE_APP_BASE_URL` gets passed in. This doesn't work in environments where the front end is built prior and shipped in a docker container (like kubernetes) **This change prevents us from having to do a custom front end build for each environment**
This will need to be used in conjunction with https://github.com/mozilla-ai/lumigator/pull/610 
Cases covered
Refs #...
Closes #...
Run `make start-lumigator-build` locally
N/A

Frontend: Change to relative backend

---

lumigator/frontend/src/helpers/index.js

Fix issue where no samples are submitted and default is used, which was causing an error in parsing in the UI when retrieving the experiment details.
2. Upload a dataset
3. Create an experiment (but **don't** set any max samples)
4. Click the created experiment in the UI and see the details panel load correctly

UI: Fix - Change the way we decide if a property is present from entrypoint config

---

.github/workflows/lumigator_pipeline.yaml
docker-compose.yaml

This PR fixes the error that we saw several times when executing `make start-lumigator`: `frontend The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`
Refs #577 
Closes #577 
Change the frontend image tag in your docker-compose to: frontend_cdeec75. I created that tag with the new process (you can also grab the one generated by the latest checks of this PR), and execute `make start-lumigator`.

Fix architecture bug

---

docs/source/operations-guide/alembic.md

Makes clear that `alembic` commands should be run using `uv`.

Docs: Update alembic guide to include `uv`

---

lumigator/python/mzai/backend/backend/tests/conftest.py
lumigator/python/mzai/backend/backend/tests/integration/api/routes/test_api_workflows.py
lumigator/python/mzai/jobs/inference/inference.py
lumigator/python/mzai/sample_data/dialogsum_mini_no_gt.csv

If a field is requested for outputs and it doesn't exist in the input dataset (which is to be expected), inference crashes (and, by extension, so does annotation).
This PR:
* copies every content from the original dataset to the new one that should be stored (so the user can always delete the previous one if they prefer)
* creates or **overwrites** the desired column. This changes the previous behaviour of keeping whatever was in the existing column (which meant we did inference for nothing if there were already predictions/annotations there).
Closes #585
1. Upload the csv listed in the issue - keep the dataset id
2. Launch via API an inference job with any model, using the dataset id
3. The inference job should succeed.
This changes the previous behaviour of …

fix: crash if requested output field for inference doesn't exist in dataset

---

Makefile
docs/source/get-started/quickstart.md

`make clean-docker-all` breaks when no containers are running because the first command `clean-docker-containers` returns an error if the list of containers is empty.
This PR fixes that by using `xargs` to pass the list (when not empty) to `docker rm` and `docker rmi`.
Closes https://github.com/mozilla-ai/lumigator/issues/660
run `make clean-all` or `make clean-docker-all`. This should remove all containers + images if present, without breaking if there is none
I am not sure why we'd need both `make clean-all` and `make clean-docker-all`. The semantics I had in mind was "clean-all should call clean-docker-all plus something else" but that does not happen (actually this is a subset of `clean-docker-all`). WDYT? Should we remove `clean-all` or is there a good reason to keep it (perhaps with …

Fix docker clean

---

lumigator/frontend/src/components/pages/LExperiments.vue

Small change to clear the state of the "details" component after use.

clear selected job upon dismissing details

---

docs/source/get-started/suggested-models.md
lumigator/python/mzai/backend/backend/config_templates.py
lumigator/python/mzai/backend/backend/models.yaml
lumigator/python/mzai/backend/backend/tests/data/models.json
lumigator/python/mzai/sdk/tests/data/models.json
notebooks/assets/model_info.csv
notebooks/walkthrough.ipynb

Remove the two models that don't perform well on generic summarization tasks.
Closes #621 
2. Open lumigator, add dataset, run experiment, observe that that `mikeadimech/longformer-qmsum-meeting-summarization` and `mrm8488/t5-base-finetuned-summarize-news` are gone.
- [ x] Tested the changes in a working environment to ensure they work as expected
- [x ] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)
- [x ] Checked if a (backend) DB migration step was required and included it if required

remove models that don't support generic summaries.

---

Makefile
lumigator/python/mzai/backend/backend/api/deps.py
lumigator/python/mzai/backend/backend/api/routes/experiments.py
lumigator/python/mzai/backend/backend/api/routes/experiments_new.py
lumigator/python/mzai/backend/backend/api/routes/jobs.py
lumigator/python/mzai/backend/backend/config_templates.py
lumigator/python/mzai/backend/backend/repositories/jobs.py
lumigator/python/mzai/backend/backend/services/experiments.py
lumigator/python/mzai/backend/backend/services/jobs.py
lumigator/python/mzai/backend/backend/tests/conftest.py
lumigator/python/mzai/backend/backend/tests/integration/api/routes/test_api_workflows.py
lumigator/python/mzai/jobs/evaluator_lite/eval_lite.py
lumigator/python/mzai/jobs/inference/inference.py
lumigator/python/mzai/jobs/inference/inference_config.py
lumigator/python/mzai/schemas/lumigator_schemas/jobs.py

The creation of datasets for a job is indicated through a new parameter in the JobInferCreate, called `store_to_dataset`. The experiment will set this when it creates the appropriate jobs.
The experiment service (used by the `experiments_new` endpoint) will now use the experiment repository and keep track of its contained jobs to provide a status.
Closes #590
An inference job that includes `store_to_dataset = True` in the job config will also add a dataset with the results. The integration tests already check this.
There are additional checks in the experiment launch about the datasets created by the experiment jobs, as well as about the experiment status. The integration test logs the experiment status for manual inspection; only the final `SUCCEEDED` or `FAILED` status are actually …

Add experiment record handling to experiment service

---

lumigator/python/mzai/backend/backend/api/routes/datasets.py
lumigator/python/mzai/backend/backend/services/datasets.py
lumigator/python/mzai/backend/backend/tests/conftest.py
lumigator/python/mzai/backend/backend/tests/fakes/fake_s3.py
lumigator/python/mzai/backend/backend/tests/unit/api/routes/test_datasets.py
lumigator/python/mzai/backend/backend/tests/unit/services/test_dataset_service.py
lumigator/python/mzai/sdk/lumigator_sdk/lm_datasets.py
lumigator/python/mzai/sdk/tests/conftest.py
lumigator/python/mzai/sdk/tests/integration/test_scenarios.py

This PR makes two changes:
1. On dataset upload we still parse the CSV to HuggingFace datasets as before, but now use the parsed files to recreate the CSV and uploads it in S3 alongside the previous HF ones (arrow and JSON).
2. The API now supports a query parameter for dataset download to filter for a specific extension (e.g. csv), the logic for this lives in the`DatasetService`.
The reason for this is that it's most likely that users (including the UI) simply want the CSV version of the dataset, either for display or to review, for example, when it is a dataset that was generated from an annotation job (where Lumigator adds ground truth for the user).
Support added to the SDK.
Closes: https://github.com/mozilla-ai/lumigator/issues/563
3. In …

API/Storage: Recreate a CSV from the uploaded dataset (CSV) and allow filtering for downloads

---

lumigator/python/mzai/backend/backend/services/jobs.py

Use the record's name, because otherwise it logs the class name and memory address.
Before change:
```
.....- Obtaining info for job ca7c4a26-2c45-4e8e-9ce6-ae1abc9b2a49: <backend.records.jobs.JobRecord object at 0xffff713e8a90>
```
After Change
```
....- Obtaining info for job ca7c4a26-2c45-4e8e-9ce6-ae1abc9b2a49: nathans_job
```
2. upload dataset
3. trigger a job, and look at the backend logs.

Use Job name instead of a reference to the address in memory.

---

lumigator/frontend/src/components/organisms/LDatasetDetails.vue
lumigator/frontend/src/components/pages/LDatasets.vue
lumigator/frontend/src/services/datasets/api.js
lumigator/frontend/src/services/datasets/datasetsService.js
lumigator/frontend/src/stores/datasets/store.js

Enables the dataset download button and downloads the CSV version of the dataset by default.
2. Upload a dataset
3. Open the dataset details pane and click the download icon (top right)

UI: Enable dataset download icon and download CSV by default

---

lumigator/frontend/src/components/molecules/LModelCards.vue
lumigator/python/mzai/backend/backend/models.yaml
lumigator/python/mzai/backend/backend/tests/data/models.json
lumigator/python/mzai/schemas/lumigator_schemas/models.py
lumigator/python/mzai/sdk/tests/data/models.json

https://github.com/mozilla-ai/lumigator/pull/689 updated the API to flag when a model required an API key.
https://github.com/mozilla-ai/lumigator/pull/691 added support for this in the UI so models could be displayed in different lists.
This PR refactors these changes to allow for more flexibility as we want to categorize models differently.
Instead of a `bool` flag returned in the API for `requires_api_key` we  can return `requirements` which contains a list (think set) of the requirements for this model. e.g. `api_key`, `llamafile`.
2. Try to create an experiment in the UI and ensure no changes to the UI
3. Try to use the [API docs](http://localhost:8000/docs#/models/get_suggested_models_api_v1_models__task_name__get) to get models for …

API/UI: Make model data more flexible for future use

---

README.md

Missing instructions to install nvidia-container-toolkit.
Related to #658
- [N/A] Added some tests for any new functionality
- [N/A] Checked if a (backend) DB migration step was required and included it if required

doc: missing nvidia-container-toolkit instructions

---

lumigator/python/mzai/backend/backend/services/datasets.py
lumigator/python/mzai/backend/backend/tests/conftest.py
lumigator/python/mzai/backend/backend/tests/unit/api/routes/test_datasets.py
lumigator/python/mzai/backend/backend/tests/unit/services/test_dataset_service.py
lumigator/python/mzai/sample_data/dialogsum_mini_all_gt_is_whitespace.csv
lumigator/python/mzai/sample_data/dialogsum_mini_some_missing_some_whitespace_gt.csv

Currently if we upload a csv with an existing ground_truth column that is empty, we consider it as having a ground-truth. Instead, we should be checking as well whether there are any values in it and return false if it's truly empty.
Closes #620 
1. git checkout this branch && git pull
1. make local-up
1. Browse to localhost (lumigator UI)
1. Upload [this CSV](https://github.com/user-attachments/files/18413388/dialogsum_mini_empty_gt.csv), which has an empty gt column (header is there, but no values)
1. See on the UI gt column set as **False**
Open to any **reasoned** choice between "ask for all rows to be annotated" and "1 sample is enough" to consider gt to be present.

fix: empty ground-truth column should mean no ground-truth

---

Makefile
lumigator/python/mzai/backend/backend/tests/conftest.py
lumigator/python/mzai/backend/backend/tests/integration/api/routes/test_api_workflows.py

Job/experiments checks are now factored in a function, that returns `True` if the job or the experiment succeeded. If the polls time out, an Exception is raised (other recommendations about how to signals timeouts are welcome).
Also, the number of polls has been reduced to 18 for a total poll time of 180 seconds (3 minutes).
Closes #643 
Run the backend integration tests with `make test-backend-integration`.
N/A

Factor out job and experiment status check loops

---

README.md
docs/source/get-started/installation.md
docs/source/get-started/suggested-models.md
docs/source/get-started/troubleshooting.md
docs/source/operations-guide/dev.md
docs/source/user-guides/inference.md
lumigator/python/mzai/backend/README.md

- there's a new section in troubleshooting re: missing API keys / tokens. It reports some of the errors one might get and how to fix this by setting up the respective env vars either in rc files or in the `.env` file
- references to API keys in readmes and documentation have been updated
- minor fixes
Closes https://github.com/mozilla-ai/lumigator/issues/579

Added API keys / tokens troubleshooting section + fixes

---

lumigator/python/mzai/backend/backend/settings.py

We previously set RAY GPU env vars as `return float(os.environ.get(self.RAY_WORKER_GPUS_ENV_VAR, 1.0))`. If the app receives an empty string for one of these vars, it won't build, because the code attempts to render the string to a float instead of assigning it `1.0` since it's not null: 
```
File "/mzai/lumigator/python/mzai/backend/backend/services/jobs.py", line 51, in JobService
2025-01-23T14:16:16.606623668Z     "ray_worker_gpus": settings.RAY_WORKER_GPUS,
2025-01-23T14:16:16.606624418Z                        ^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-23T14:16:16.606625126Z   File "/mzai/lumigator/python/mzai/backend/backend/settings.py", line 120, in RAY_WORKER_GPUS
2025-01-23T14:16:16.606640710Z     return float(os.environ.get(self.RAY_WORKER_GPUS_ENV_VAR, 1.0)) …
```

Ray env var empty string fix

---

Dockerfile

The Jobs folder needs to be watched by uvicorn so that it hot reloads when you make changes. Thanks @HareeshBahuleyan  for the find!

HotReload for Jobs in Dev Mode

---

lumigator/frontend/src/components/molecules/LExperimentDetails.vue

This PR fixes a new bug where experiment details don't show max samples correctly and instead show the entire JSON object for the selected experiment.
2. http://localhost
3. Upload a dataset with ground truth
4. Create an experiment with the dataset (enter max samples, or don't, or make two experiments with each)
5. Once created view the experiment details panel on the right hand side and samples limit should show correctly

[BUG] UI: Experiment details doesn't show max samples correctly

---

lumigator/python/mzai/backend/backend/tests/integration/api/routes/test_api_workflows.py

We inadvertently dropped an integration test in end-to-end testing while merging this PR: https://github.com/mozilla-ai/lumigator/pull/632, adding these back in. Local testing works. 
Run `make test-backend-integration` :```7 passed, 17 warnings in 289.60s (0:04:49)```

Fix integration tests for backend API 

---

.github/workflows/build_and_publish_docs.yaml
docs/source/conceptual-guides/endpoints.md
docs/source/conf.py
docs/source/get-started/installation.md

We need to check the links every build, not only when the docs change. This is because maybe the docs didn't change but the link it points to did! In order to catch that, we need to check the links every time. In order to check the links, we need to check the compiled sphinx docs, because the sphinx docs MD files use dynamic links that insert the GIT commit that ties it to the right file version. So we need to run the link checker on the compiled html.

Fix link checker

---

lumigator/backend/backend/api/routes/datasets.py
lumigator/backend/backend/services/datasets.py
lumigator/backend/backend/services/exceptions/base_exceptions.py
lumigator/backend/backend/services/exceptions/dataset_exceptions.py
lumigator/backend/backend/tests/conftest.py
lumigator/backend/backend/tests/integration/api/routes/test_api_workflows.py
lumigator/backend/backend/tests/unit/services/test_job_service.py
lumigator/backend/uv.lock

More dataset errors returned from the `dataset_service`.
* When the dataset is not found when getting the S3 path (`DatasetNotFoundError`)
* When the dataset identified to a job ID (run ID) is not available (`DatasetNotAvailableError`)
`DatasetNotAvailableError` is mapped to [HTTP status code `422`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422) 
> The HTTP 422 Unprocessable Content [client error response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses) status code indicates that the server understood the content type of the request content, and the syntax of the request content was correct, but it was unable to process the contained instructions.
>Clients that receive a 422 response should expect that repeating the request without …

Backend: Dataset errors

---

infra/helm/lumigator/charts/backend/Chart.yaml
infra/helm/lumigator/charts/frontend/Chart.yaml

It looks like a change in https://github.com/mozilla-ai/lumigator/pull/745 introduced a regression which breaks the front end nginx container being able to find the backend container (Chart name dictates the name of the backend service, which changed when the chart name changed)
Helm install

[Hotfix] Chart name regression breaks frontend/backend communication

---

.github/workflows/lumigator_pipeline.yaml

Due to the second pipeline iteration, I changed how we build and push the images to DockerHub. I introduced an intermediate registry in order to build the images at the same time we are executing the tests. After all tests have passed, the action downloads the image from the intermediate  registry, and pushes it to DockerHub. In that step, we lost the multi-platform image, because the runner is downloading the one accordingly to its architecture.
Run `make start-lumigator` changing backend image tag to: `backend_dev_95ebf41`. That's the tag of the last pipeline execution of this PR, you can check it.
N/A

Fixing multiplatform build

---

Makefile
docker-compose.yaml

Ensure `make start-lumigator` command always pulls the latest docker image versions before starting, as a way to avoid the need for manually removing and rebuilding images
1. run `make start-lumigator`
2. potentially push a new version of the docker image
3. run `make start-lumigator` again and ensure that the latest version is running and that the new image has been pulled
Or just double check that docker attempts to pull the images before running

build: always pull latest docker image before start-lumigator

---

Makefile

Ensures that we do the same thing when we `make local-down` we did to `local-up`, this PR means that MLFlow is removed now when you `local-down`.
The current [local-up docker cmd](https://github.com/mozilla-ai/lumigator/pull/813/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R111):
```bash
docker compose --profile local $(GPU_COMPOSE) -f $(LOCAL_DOCKERCOMPOSE_FILE) -f ${DEV_DOCKER_COMPOSE_FILE} up --watch --build
```
2. `make local-down`
3. Everything should be removed from the containers in Docker

Makefile: match `local-up` profiles and compose files, in `local-down`

---

lumigator/backend/backend/api/routes/experiments.py

We have unit/integration testing around the new experiments (e.g. /experiments/new and /workflows) but apparently not for the old experiments endpoint 🙈 
Please feel free to approve and merge this without me, since this is needed to get the frontend working (the frontend is the only thing using the old experiments endpoint.

Bugfix for old experiments endpoint

---

docker-compose.yaml

Quickfix for https://github.com/ray-project/ray/issues/32167
The name of the env var is not correctly set in the Ray container entrypoint.

Fix name of Ray cluster env var

---

ruff.toml

Updates the max line length from `100` characters to `120`.
79 characters mentioned in [pep-0008](https://peps.python.org/pep-0008/#maximum-line-length) was already too small.

Update max line length from 100 chars to 120 as a treat in 2025

---

lumigator/backend/backend/api/routes/jobs.py
lumigator/backend/backend/config_templates.py
lumigator/backend/backend/services/exceptions/job_exceptions.py
lumigator/backend/backend/services/jobs.py
lumigator/backend/backend/tests/unit/services/test_job_service.py
lumigator/jobs/inference/inference_config.py
lumigator/jobs/inference/model_clients.py
lumigator/jobs/inference/schemas.py
lumigator/schemas/lumigator_schemas/jobs.py

Add support for models filtered by the "text-generation" tag on the HF Hub. This means adding support for causal models, such as Llama, Gemma, Qwen, etc.
Causal models can complete a wide variety of tasks; therefore, users should provide a proper system prompt to inform the models about the task at hand. The user-provided system prompt, along with the data, is then transformed into a model-specific prompt using the chat template defined in the tokenizer config (a Jinja2 string template). This step will fail for older models, which don't have a defined chat template.
Refs #122
1. Deploy Lumigator with `make local-up`
2. Upload a dataset through the OpenAPI UI.
3. Create an inference job with the following body:
```json
{
"name": "string",
"model": …
```

Add support for HF text-generation pipelines

---

docs/source/index.rst
docs/source/operations-guide/configuration.md

Fix the way note is displayed in configuration page of docs, and update navigation to show the page.
Refs #812

Show configuration in operational guide menu

---

docker-compose.yaml
lumigator/backend/backend/services/jobs.py
lumigator/backend/backend/settings.py
lumigator/backend/backend/tests/unit/services/test_job_service.py
lumigator/jobs/inference/inference.py
lumigator/jobs/inference/model_clients.py

Add support for invoking the DeepSeek API, using the OpenAI Python client.
See here: https://api-docs.deepseek.com/
Closes #869
1. Grab your DeepSeek API key and export it:
```bash
export DEEPSEEK_API_KEY=<your-key>
```
1. Deploy Lumigator with `make local-up`.
1. Upload a dataset using:
```bash
#!/bin/bash
if [ "$#" -gt 0 ]; then
DATA_CSV_PATH="$1"
else
DATA_CSV_PATH="<data-path>"
fi
if [[ -z "${BACKEND_URL}" ]]; then
BACKEND_URL=http://localhost:8000
fi
echo Connecting to $BACKEND_URL...
curl -s $BACKEND_URL/api/v1/datasets/ \
-H 'Accept: application/json' \
-H 'Content-Type: multipart/form-data' \
-F 'dataset=@'"$DATA_CSV_PATH"';type=text/csv' \
-F 'format=job' | jq
```
1. Run an inference job:
```bash
if [[ -z "${BACKEND_URL}" ]]; then …
```

inference: Support invoking DeepSeek API (#869)

---

lumigator/frontend/src/components/datasets/LDatasetEmpty.vue
lumigator/frontend/src/components/experiments/LExperimentTable.vue
lumigator/frontend/src/sdk/workflowsService.ts
lumigator/frontend/src/stores/experimentsStore.ts

Closes https://github.com/mozilla-ai/lumigator/issues/875 , part of https://github.com/mozilla-ai/lumigator/issues/885
Fixes an issue with polling/updating the experiment and workflow level statuses on creating a new experiment
1. Create a new Experiment with workflows
2. The experiment status and workflow status should now update without having to refresh the page

fix: fix polling for workflow/experiment status

---

lumigator/backend/backend/services/jobs.py
lumigator/backend/backend/services/workflows.py

Dataset saving is triggered inside the JobService only on inference jobs which explicitly provide a True `store_to_dataset` config variable.
Within an inference + evaluation workflow, inference jobs are called with an explicit `store_to_dataset`=False and dataset saving is immediately enqueued afterwards to guarantee the dataset is present before evaluation.
Closes https://github.com/mozilla-ai/lumigator/issues/877
1. run a full workflow on a dataset with GT
2. verify that there's exactly one dataset generated by the inference job 
3. run an annotation job on a dataset without GT
4. verify that there's exactly one dataset generated by the inference job

Refactored dataset saving for inference jobs

---

.default.conf
docker-compose.yaml

Fixed the use of HF_HOME in configs to properly cache HF models from ray container into HF_HOME directory:
- [`HF_HOME`](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/environment_variables#hfhome) is the env variable that HF looks into to know where e.g. to store its cache
- we'd like to mount host `HF_HOME` to ray's
- we define `HF_HOME` in `.default.conf` just for the sake of knowing where the host HF cache is (likely the default, but users can change it here if they have chosen another place for it)
- we mount `HF_HOME` to `/home/ray/.cache/huggingface` inside the ray container, so all models downloaded in there will be cached locally
- we don't make `HF_HOME` env var available in the container, as using the system default is fine there.
> If this PR is related …

Fixed HF_HOME for HF cache into ray

---

lumigator/jobs/inference/model_clients.py

@aittalam mentioned some docs updates needed for LiteLLM and while answering that question I realized there is a bug in the code where we're not using the provider key in LiteLLM. this doesn't cause any issues when the provider is OpenAI compatible but does raise issues if using the deepseek api, mistral, etc.
Refs #956 

LiteLLM should use the provider key

---

.default.conf
cache/Dockerfile.model-inference
cache/download_models.py
docker-compose.yaml

- updated model name to `roberta-large` in config (the FacebookAI one is the same but bertscore reads the one with no company name from cache)
- fixed Dockerfile and docker-compose to run downloads in container and not at image-creation time
- updated download_models.py to provide meaningful updates to the users

A few changes to enable model preloading

---

docker-compose.yaml

We're changing how we run start-lumigator to ensure we always pick the latest version of the containers. As it happened twice, we've made important changes to the environment variables in our docker-compose for ray. The tag for the backend and frontend container have code that need the variables in an older version (the same git tag as the containers).
This prs ensures we always point to the latest images in the containers

Changed containers in docker-compose to use latest tag

---

Makefile
docker-compose.yaml
docs/source/operations-guide/configuration.md
lumigator/backend/backend/settings.py
scripts/common.sh
scripts/config_generate_env.sh
scripts/config_generate_key.sh
scripts/setup_uv.sh

On starting Lumigator via `make local-up` or `make start-lumigator*` we now check for the existence of a key file in the Lumigator 'dot folder' in the user's home folder (`~/.lumigator/lumigator.key`). 
If the key isn't found we generate it and store it.
The key is used to create the temp `.env` file supplied to Docker Compose for deployment, which sets the `LUMIGATOR_SECRET_KEY` on the Backend container (and the backend app pulls it into it's settings).
Closes #948 
* Start Lumigator and check the terminal output:
```bash
make local-up
```
* Check the generated key value (to compare with the rest):
```bash
cat ~/.lumigator/lumigator.key
```
* Check the `build/.env` file: 
```bash
cat build/.env | grep LUMIGATOR_SECRET_KEY
```
* Check the docker compose output: …

Settings: Support generation/usage of encryption key

---

lumigator/backend/backend/services/jobs.py

I made https://github.com/mozilla-ai/lumigator/pull/972 a little big, so I'm going to split this into some smaller more manageable chunks.
Our SamplingParameters should apply whether using the HF Pipeline or the LiteLLM pipeline for the inference job
Refs #970

[BUG] Sampling parameters were only being applied to LiteLLM, not HFPipeline

---

docs/source/get-started/quickstart.md

* Fixed a typo in quickstart.md, the link of the Swaggert HTTP docs was "http://localhost:8O00/docs" instead of "http://localhost:8000/docs"

Fixed a typo in quickstart.md file

---

docs/source/user-guides/local-models.md

[In our docs](https://github.com/mozilla-ai/lumigator/blob/main/docs/source/user-guides/local-models.md?plain=1#L87) we link to https://openwebui.com/, which is sometimes down and makes our doc build fail and look sad.
We can just as easily link to https://github.com/open-webui/open-webui , which is more often up and provides equally helpful information.
Test the link :) See the rendering of the markdown page.
- [ X] Tested the changes in a working environment to ensure they work as expected
- [ NA] Added some tests for any new functionality
- [ X] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)
- [ X] Checked if a (backend) DB migration step was required and included it if required

doc: fix webui link

---

lumigator/frontend/nginx/default.conf.template

Ensure our Nginx matches the max_dataset_size we have currently in the backend
Refs #1049 
Closes #1049 
1. Upload a dataset that's bigger than 2 MB but smaller than 50MB
Getting exactly 50MB will probably fail , around 48MB will work
- [ X] Tested the changes in a working environment to ensure they work as expected
- [ X] Checked if a (backend) DB migration step was required and included it if required

Modified lumigator nginx size limit to 50mb

---

lumigator/jobs/inference/model_clients.py
notebooks/requirements.txt

HuggingFaceModelClient initialization and inference logic was based purely on task.
This PR updates it to be conditional based on task and whether the model is seq2seq.
This is because for seq2seq models (e.g. BART), we can call the HF pipeline with specific tasks like summarization or translation.
But for CausalLM models (e.g. Llama), HF pipeline should be called with the task as the generic "text-generation". Whether to perform summarization or translation or something else would be dictated by the system_prompt. 
Also if we call CausalLM pipepine with task as "summarization", it throws the following error:
```
ValueError: Unrecognized configuration class <class 'transformers.models.llama.configuration_llama.LlamaConfig'> for this kind of AutoModel: AutoModelForSeq2SeqLM.
Model type …
```

HuggingFaceModelClient logic based on whether the model is seq2seq or Causal LM

---

.default.conf

The default location for the DB is restored to the mounted `/db-data/local.db` path.
Closes #1077 
1. Start Lumigator
2. Upload a dataset and perform an experiment
3. Restart Lumigator
4. The dataset and experiment data should still be present
N/A
- No DB change needed

Fix DB default location

---

lumigator/schemas/lumigator_schemas/tests/unit/test_job_submission_response_transform.py
lumigator/schemas/lumigator_schemas/transforms/job_submission_response_transform.py
lumigator/schemas/pyproject.toml

If the config dictionary supplied to the function parsing model name or path has the right keys, but null/None values we experienced an exception.
This PR fixes the bug and adds some other defensive lines of code and unit tests.
Refs: #933
1.
2.
3.

Settings: Fix redaction bug in parsing model name/path

---

lumigator/backend/backend/services/jobs.py
lumigator/backend/backend/services/workflows.py

Annotations now use `{original}-annotated.csv` as filename for results, whereas inferences use `{original}-{model}-predictions.csv`,
Closes #897 
Try out annotations and evaluations, and check that the dataset names are according to the jobs performed.
N/A
- No DB change needed.

Fix generated dataset filenames

---

.default.conf
docker-compose.yaml

Mlflow was mapping to a sqlite location that wasn't persisted outside the container, meaning that it would be reset whenever the container was removed or re-created.
Refs #1135 
1. `make start-lumigator-build`
2. `run experiment + workflow`
3. `make stop-lumigator`
4. `make start-lumigator-build`
5. Check the UI / Mlflow and see that everything is still there.

[BUG] Mlflow data was not being persisted on container recreation

---

docs/source/index.rst
docs/source/operations-guide/vllm-rayserve-deployment.md
infra/helm/inference-service/Chart.yaml
infra/helm/inference-service/README.md
infra/helm/inference-service/templates/_helpers.tpl
infra/helm/inference-service/templates/inference-service.yaml
infra/helm/inference-service/values.yaml
lumigator/rayserve/README.md
lumigator/rayserve/serve.py

Introduce the Helm Chart and Python source code to deploy any vLLM-supported model on a Kubernetes cluster, using vLLM and Ray Serve.
Refs #952
Follow the corresponding operations guide, available in the PR.

Deploy a Model with vLLM and Ray Serve

---

lumigator/backend/backend/services/workflows.py
lumigator/frontend/src/components/views/Settings.vue
lumigator/frontend/src/sdk/experimentsService.ts
lumigator/frontend/src/types/Workflow.ts

Now that jobs and workflows can be given the secret key name to grab from Lumigator and supply to underlying jobs, the UI needs to support sending in the right secret name key based on the provider.
UI has strong opinions on the name of settings saved via the UI following the format: `{provider}_api_key` and this PR continues that.
Refs: https://github.com/mozilla-ai/lumigator/issues/924
One thing we might decide later is to include some copy/content on the site explaining which settings need to be saved before you run the experiments.
1.
2.
3.

UI: Pass secret key names for each workflow based on the provider it is targetting

---

lumigator/frontend/src/sdk/experimentsService.ts

Fixes typo and adjusts the syntax to make it a bit easier to read.

UI: fix to use `api_key` instead of `api-key`

---

lumigator/backend/backend/services/exceptions/base_exceptions.py

Fix the missing call to the Exception base class to supply the message in service exceptions.

Services: exceptions missing call to base class init

---

docs/source/get-started/suggested-models.md
lumigator/backend/backend/models.yaml
lumigator/backend/backend/tests/integration/api/routes/test_api_workflows.py
lumigator/backend/backend/tests/unit/api/routes/test_jobs.py
lumigator/backend/backend/tests/unit/services/test_job_service.py
notebooks/walkthrough.ipynb

At the end of this month, Mistral is retiring one of the models we offer via API (Mistral-7B). Ministral-8B is its replacement. This PR simply does the switch and updates info + tests.
Closes #569
There are tests targeting this model. In addition, any custom script that was using M-7B should just as easily use Ministral-8B instead.
- [ X] Tested the changes in a working environment to ensure they work as expected
- [X ] Added some tests for any new functionality
- [X ] Updated the documentation (both comments in code and [product documentation](https://mozilla-ai.github.io/lumigator) under `/docs`)
- [ NA] Checked if a (backend) DB migration step was required and included it if required

feat(models): replaced deprecated mistral-7B with ministral -8B

---

.github/workflows/build_and_publish_docs.yaml

Don't use the caching model container for the docs OpenAPI update
Refs: https://github.com/mozilla-ai/lumigator/pull/1183
Refs: https://github.com/mozilla-ai/lumigator/pull/1187

GHA: Disable inference model cache for docs

---

.devcontainer/docker-compose.override.yaml

Adds some more paths to ignore when running the containers in `watch` mode (via `make local-up`).
This prevents the app trying to reload when things inside the `.venv`, test or cache folders change.

DevEx: Update dev container overrides to ignore more .venvs and test folders

---

Makefile

The wrong location for the SQL Alchemy env var was being set in the `Makefile`, overriding the defaults present in the `.default.conf` file.
Closes #928 
1. Start Lumigator
2. Perform some annotation job or an experiment
3. Close Lumigator and start it again
4. Jobs from step 2 should still be visible
N/A
- No DB changes needed

Remove Alchemy DB env var in Makefile

---

.github/workflows/lumigator_pipeline.yaml

When integration tests fail, we sometimes see errors in uploading the logs in GitHub Actions.
It seems that in `v4` of `actions/upload-artifact`:
> users lose the ability to upload to the same named artifact multiple times. Once an artifact is uploaded cannot be altered, and there cannot be multiple v4 artifacts with the same name, in the same workflow run.
See: https://github.blog/news-insights/product-news/get-started-with-v4-of-github-actions-artifacts/#compatibility
This seems to align with what we see in the GitHub Actions runner output:
```console
Run actions/upload-artifact@v4
With the provided path, there will be 90 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an …
```

GHA: Adjust names for failed logs

---

lumigator/backend/backend/models.yaml
lumigator/backend/backend/tests/integration/api/routes/test_api_workflows.py
lumigator/jobs/inference/model_clients/external_api_clients.py

In the inference job, if no `api_key` environment variable has been set, `None` will be passed to LiteLLM as the value for the API key. Apparently, the OpenAI client does not interpret this correctly in the case of non-authenticated OpenAI-compatible endpoints like Llama, and needs some dummy value for the API key.
See https://github.com/BerriAI/litellm/issues/3225#issuecomment-2733944679 for more context.
Closes #1201 
Create a new Experiment using a Llamafile-served model, like Mistral. It should not yield `AuthenticationError`and work normally.
Note that HTTP requests passed by e.g. `curl` without any kind of Auth headers will run ok. This seems a limitation of the OpenAI client itself (used by LiteLLM).
N/A

Add default api key if none is provided

---

lumigator/backend/backend/services/jobs.py

This PR fixes a bug where the first call to `jobs/{job_id}/logs` retrieved all current logs for the job, but subsequent calls returned the same value as the first call. 
We now try to get updated logs from Ray when possible, and fallback to returning what we have stored in the DB if Ray returns us errors.
Closes #1088 
2. Upload a dataset and create an experiment
3. Click on one of the jobs in the experiment, and click logs from the right hand side panel... watch and wait for logs

Job Logs: Fix bug where logs were not updated after first check

---

lumigator/schemas/lumigator_schemas/tests/conftest.py
lumigator/schemas/lumigator_schemas/tests/data/workflow_results.json
lumigator/schemas/lumigator_schemas/tests/data/workflow_results_overlay_all.json
lumigator/schemas/lumigator_schemas/tests/data/workflow_results_overlay_artifacts_missing.json
lumigator/schemas/lumigator_schemas/tests/data/workflow_results_overlay_artifacts_same.json
lumigator/schemas/lumigator_schemas/tests/unit/test_utils_model_operations.py
lumigator/schemas/lumigator_schemas/utils/model_operations.py

Adds `merge_models` from `model_operations` as a schema util that allows you to merge two of the same Pydantic models (including a deep merge). 
It returns the resulting merged model ... along with some sets identifying:
* Overwritten keys that appeared in both models and the values were different
* Un-merged keys that only appeared in the base model and not the overlay (they are present in the final model)
* Skipped keys that existed in both, but already had the same value
Added tests to cover the functionality.
Unit tests in the PR cover testing.
This can be used to merge job results in the MLFlow tracking client when it attempts to generate the compiled results for a workflow.

Schema: Add schema util that allows merging of Pydantic schema models

---

docs/source/get-started/quickstart.md
docs/source/reference/schemas.rst
docs/source/user-guides/translation-eval.md

Update the docs to reflect the latest `workflow` schema changes (#1104), where a workflow inherits the `dataset`, `max_samples`, and `task_definition` attributes from the experiment it references.
Closes #1251

Update docs to reflect the latest workflow schema changes

---

lumigator/frontend/src/helpers/getExperimentResults.ts
lumigator/frontend/src/types/Metrics.ts

When running evaluation via the SDK or API, users can select a subset of metrics -> this PR renders only the chosen metrics
Refs #...
Closes #...
1.
2.
3.

fix: dont render metrics columns if they're null/undefined

---

.github/workflows/lumigator_pipeline.yaml
.pre-commit-config.yaml
Makefile
pyproject.toml
uv.lock

* Update version of pre-commit to 4.2.0 (from 4.1.0)
* Ensure makefile forces the version of pre-commit specified in the pyproject.toml
* Refactor GHA pipeline to use uv more
* Add uv.lock to pre-commit checks
* Update uv.lock file
1.
2.
3.
Running `uv sync` will install the version of Python specified in the repo, create a .venv and source it for us.
We still run `uv run pre-commit install` to install the git hooks for pre-commit.

`pre-commit`: fixes/updates

---

lumigator/backend/backend/api/routes/experiments.py
lumigator/backend/backend/api/routes/workflows.py
lumigator/backend/backend/services/datasets.py
lumigator/backend/backend/services/experiments.py
lumigator/backend/backend/services/workflows.py
lumigator/backend/backend/tests/conftest.py
lumigator/backend/backend/tracking/mlflow.py
lumigator/backend/backend/tracking/tracking_interface.py
lumigator/backend/pyproject.toml
lumigator/backend/uv.lock
pyproject.toml
uv.lock

* Update the Tracking Client interface to be async for all methods by default
* Update MLFlow Tracking Client to adhere to the updated interface
* Bubble up async calls through services and routes (workflows, experiments)
* Configure S3FileSystem used for tests (via MagicMock) to emulate the correct params for 'storage_options'
* Remove un-required (s3 related) dependencies, and update dependencies from backend's pyproject.toml
* Fix: Add 'integration' pytest marker to test config to prevent warnings being emitted during test runs
* Chore: uv.lock updated
Refs: https://github.com/mozilla-ai/lumigator/pull/1252
1.
2.
3.
Anything …

Fix async issues after moving to S3FileSystem from boto3 client

---

lumigator/backend/backend/services/workflows.py
lumigator/backend/backend/tests/unit/tracking/test_mlflow.py
lumigator/backend/backend/tracking/mlflow.py
lumigator/backend/backend/tracking/tracking_interface.py
lumigator/backend/pyproject.toml

* Updates the status of the run in MLFlow as well as the tag we create for status.
1.
2.
3.
This is the 'status' shown in MLFlow when we don't come back to update it at the end:
Now the status no longer says 'Running'
So we can see what was successful/failed in the MLFlow dashboard too:

Tracking client: update MLFlow run status when we update the status tag

---

lumigator/backend/backend/services/jobs.py
lumigator/backend/backend/services/workflows.py
lumigator/backend/backend/tests/integration/api/routes/test_api_workflows.py
lumigator/backend/backend/tests/unit/services/test_job_service.py
lumigator/backend/backend/tracking/mlflow.py
lumigator/jobs/evaluator/evaluator.py
lumigator/jobs/evaluator/tests/test_eval_metrics.py
lumigator/jobs/inference/inference.py
lumigator/jobs/inference/inference_config.py
lumigator/jobs/inference/schemas.py
lumigator/jobs/inference/tests/test_inference.py
lumigator/schemas/lumigator_schemas/jobs.py
lumigator/sdk/tests/integration/test_scenarios.py

* Fixes the schemas: `InferenceJobOutput`, `InferenceMetrics`, `PredictionResult` and `JobOutput` within `jobs/`
* Removes the extra list comprehension in metrics calculation, extracts average calculation to function and adds tests
* Align S3 paths for jobs, try to re-use functions to create URIs and pass in fully qualified storage paths when submitting jobs
* Sanitize S3 filename to prevent forward slashes and other awkward characters
* Inference and Evaluation jobs updated (mostly based on S3 tweaks)
1.
2.
3.

Update schemas, align job results S3 paths, refactor inference metrics calc

---

docs/source/user-guides/local-models.md

VLLM project [moved their docker files](https://github.com/vllm-project/vllm/pull/14549) to `docker/`, this PR updates the docs links.
1. If the GHA tests all pass, we're good.

Update docs to fix broken links

---

lumigator/backend/backend/api/routes/workflows.py
lumigator/backend/backend/services/workflows.py

Await result for `get_workflow` as part of calling `delete_workflow`.
Closes: #1308
Refs: https://github.com/mozilla-ai/lumigator/pull/1288
1.
2.
3.

Fix: `delete_workflow`

---

lumigator/backend/backend/services/jobs.py
lumigator/backend/backend/tests/conftest.py
lumigator/backend/backend/tests/integration/api/routes/test_api_workflows.py
lumigator/jobs/inference/model_clients/external_api_clients.py
lumigator/sdk/tests/integration/test_scenarios.py

Updated integration test that wasn't setting the correct config key for passing the API key/secret. 
The test was calling Ray for real and the jobs fail out with auth errors trying to contact Mistral's API. The test has been updated to remove some bits we didn't need and just check the test fails as expected. 
The inference job now also checks if any prediction responses are errors and raises them.
Summary:
* JobService: use sets and fix IDE warning
* conftest: improve wait_for_job code
* Inference: Raise errors in prediction results (Ray)
* Review test_launch_job_with_secret integration test
1.
2.
3.

Ray: raise API auth errors from inference jobs

---

uv.lock

Seems to have been missed (https://github.com/mozilla-ai/lumigator/pull/1325) but pre-commit picked it up and updated it when I ran this locally:
```
uv run pre-commit run --all-files
```
Refs https://github.com/mozilla-ai/lumigator/pull/1325

Fix: uv.lock file update (out of date)
